export const mock = [
    {
        "id": "1",
        "country": "Greece",
        "location": "Seaside",
        "name": "Villa Luna",
        "guests": "11 guests",
        "bedrooms": '6 bedrooms',
        "area": "120 m2",
        "bathrooms": '25 bathrooms',
        "image": "images/Luna.svg",
        "price": "From €350 / daily",
    },
    {
        "id": "2",
        "country": "Italy",
        "location": "Mountains",
        "name": "Villa Tosca",
        "guests": "8 guests",
        "bedrooms": '8 bedrooms',
        "area": "460 m2",
        "bathrooms": '4 bathrooms',
        "image": "images/Tosca.svg",
        "price": "From €350 / daily",
    },
    {
        "id": "3",
        "country": "Greece",
        "location": "Seaside",
        "name": "Aphrodite",
        "guests": "12 guests",
        "bedrooms": '6 bedrooms',
        "area": "460 m2",
        "bathrooms": '5 bathrooms',
        "image": "images/Aphrodite.svg",
        "price": "From €350 / daily",
    }, 
    {
        "id": "4",
        "country": "Italy",
        "location": "Mountains",
        "name": "Makarska",
        "guests": "8 guests",
        "bedrooms": '8 bedrooms',
        "area": "460 m2",
        "bathrooms": '4 bathrooms',
        "image": "images/Makarska.svg",
        "price": "From €280 / daily",
    }, 
    {
        "id": "5",
        "country": "Greece",
        "location": "Seaside",
        "name": "Roxane",
        "guests": "11 guests",
        "bedrooms": '6 bedrooms',
        "area": "120 m2",
        "bathrooms": '25 bathrooms',
        "image": "images/Roxane.svg",
        "price": "From €110 / daily",
    }, 
    {
        "id": "6",
        "country": "Greece",
        "location": "Seaside",
        "name": "Aphrodite",
        "guests": "12 guests",
        "bedrooms": '6 bedrooms',
        "area": "460 m2",
        "bathrooms": '5 bathrooms',
        "image": "images/Aphrodite_2.svg",
        "price": "From €240 / daily",
    }, 
    {
        "id": "7",
        "country": "Italy",
        "location": "Mountains",
        "name": "Sunset",
        "guests": "8 guests",
        "bedrooms": '8 bedrooms',
        "area": "460 m2",
        "bathrooms": '4 bathrooms',
        "image": "images/Sunset.svg",
        "price": "From €280 / daily",
    }, 
    {
        "id": "8",
        "country": "Greece",
        "location": "Seaside",
        "name": "White Lady",
        "guests": "11 guests",
        "bedrooms": '6 bedrooms',
        "area": "120 m2",
        "bathrooms": '25 bathrooms',
        "image": "images/White_lady.svg",
        "price": "From €110 / daily",
    }, 
    {
        "id": "9",
        "country": "Greece",
        "location": "Seaside",
        "name": "Thebes",
        "guests": "12 guests",
        "bedrooms": '6 bedrooms',
        "area": "460 m2",
        "bathrooms": '5 bathrooms',
        "image": "images/Thebes.svg",
        "price": "From €240 / daily",
    }, {
        "id": "10",
        "country": "Italy",
        "location": "Mountains",
        "name": "Villa Tosca",
        "guests": "8 guests",
        "bedrooms": '8 bedrooms',
        "area": "460 m2",
        "bathrooms": '4 bathrooms',
        "image": "images/Tosca.svg",
        "price": "From €350 / daily",
    },
]